VistaEDI.2.Web/Controllers/GridController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using VistaEDI._2.Model;
using VistaEDI._2.Data;


namespace VistaEDI._2.Web.Controllers
{
    public class GridController : Controller
    {
        // GET: Grid
        public ActionResult GetDeviationList(DataGridoption option)
        {
            //List<DeviationList> lstDeviation = null;
            List<DeviationsViewModel> lstDeviation = null;
            // DeviationList deviationList = new DeviationList();
            DeviationsViewModel deviationList = new DeviationsViewModel();
            int total = 0;
            try
            {
                lstDeviation = new ParserData().GetList(option);
                total = lstDeviation.Count();
                return Json(new { items = lstDeviation, total = total }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                lstDeviation = null;
                total = 0;
                throw ex;
            }

           
        }
    }
}

VistaEDI.2.Web/Controllers/ParserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VistaEDI._2.BL;
using VistaEDI._2.Model;
using System.IO;

namespace VistaEDI._2.Web.Controllers
{

    public class ParserController : Controller
    {

        // GET: Parser
         public ActionResult Index()       
        {    
            return View();
        }

        [HttpPost]
       public ActionResult Upload(HttpPostedFileBase file, char status = '1')
        {
            bool isDeviation = false;
            if (status != '0')
            {
                if (file != null && file.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(file.FileName);
                    BinaryReader b = new BinaryReader(file.InputStream);
                    byte[] binData = b.ReadBytes(file.ContentLength);
                    string result = System.Text.Encoding.UTF8.GetString(binData);
                   

                    ResultViewModel message = new VistaParser().ParseJson(result, status);

                    if (message.Success)
                    {
                        if (message.Message != "")
                        {
                            message.Message = "Deviations: " + message.Message;
                            ViewBag.Message = message.Message;
                            ViewBag.Status = "Choose Status and file to Accept/Reject with deviation ";
                            isDeviation = true;
                        }
                        else
                            ViewBag.Message = "File successfully uploaded";
                    }
                    else
                    {
                        ViewBag.Message = "File upload ERROR ";
                    }
                   
                }
                else
                {
                    ViewBag.Message = "File not selected";
                }
            }
            else
            {
                ViewBag.Message = "Upload Rejected";
            }
                
            if (isDeviation)
            {
                return RedirectToAction("DeviationList");
            }
                            
            return View("Index");
        }

        #region Deviation

        public ActionResult DeviationList()
        {            
            return View();
        }
        
        public ActionResult DeviationListUpdate(int RecId, char status = '2')
        {
            ResultViewModel result = new ResultViewModel();
          //  bool isSuccess = false;
            
            try
            {
                //status = '3' : Accept on Deviation
                //status = '0' : Reject on Deviation
                result = new VistaParser().AcceptOrReject(status, RecId);
            }           
           catch(Exception ex)
            {
                result.Message = ex.Message;
            }
         
              return Json(new { isSuccess = result.Success, message = result.Message }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult DeleteRecords(string selectedRecords)
        {
            ResultViewModel result = new ResultViewModel();
            //  bool isSuccess = false;

            try
            {
                    result = new VistaParser().DeleteRecords(selectedRecords);
            }
            catch (Exception ex)
            {
                result.Message = ex.Message;
            }

            return Json(new { isSuccess = result.Success, message = result.Message , message1 = result.Message1}, JsonRequestBehavior.AllowGet);
        }

   
        //private static int splitRec(string records, int count)
        //{
        //    int record = 0;
        //    if (!string.IsNullOrEmpty(records))
        //    {
        //        // string[] recordsSplit = records.Split(new char[] { ';' }, StringSplitOptions.RemoveEmptyEntries);
        //        string[] recordsSplit = records.Split(new char[] { ',' }, StringSplitOptions.RemoveEmptyEntries);
        //        record = Convert.ToInt32(recordsSplit[count]);
        //    }
        //    return record;
        //}

        #endregion
    }


}

VistaEDI.2.Web/Views/Parser/DeviationList.cshtml
@{
    ViewBag.Title = "DeviationList";
}
<div class="panel-heading">List of Deviated Records</div>
<div class="panel-body">

    <div id="searchDiv" class="container">        
       @* <form action="ExportToExcel" method="post">*@
            <div class="row">
                <div class="col-md-3">
                    <div class="form-group">
                        <label for="searchHeatNo" class="cols-sm-2 control-label">Heat Number</label>
                        <div class="cols-sm-10">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-search" aria-hidden="true"></i></span>
                                <input type="text" value="" id="searchHeatNo" name="searchHeatNo" class="form-control" placeholder="Enter Heat Number" />
                            </div>
                        </div>
                    </div>
                </div>
                @*<div class="col-md-3">
                    <div class="form-group">
                        <label for="searchStatus" class="cols-sm-2 control-label">Status</label>
                        <div class="cols-sm-10">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-search" aria-hidden="true"></i></span>
                                <input type="text" value="" id="searchStatus" name="searchStatus" class="form-control" placeholder="Enter Status" />
                            </div>
                        </div>
                    </div>
                </div>*@
            </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <button id="btnDeleteAll" class="btn btn-danger btn-sm pull-right cust-left-margin" style="margin-left:10px!important"><i class="fa fa-trash" aria-hidden="true"></i>Delete All</button>
                    <button id="btnSelectDelete" class="btn btn-warning btn-sm pull-right"><i class="fa fa-trash" aria-hidden="true"></i>Delete Selected</button>
                </div>
            </div>
        </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="" class="cols-sm-2 control-label"></label>
                        <div class="cols-sm-10">
                            <button id="btnSearch" class="btn btn-primary btn-large" onclick="return false;"><i class="fa fa-search" aria-hidden="true"></i> Search</button>
                            &nbsp;&nbsp;&nbsp;
                            <button id="btnClear" class="btn btn-primary btn-large" onclick="return false;"><i class="fa fa-times" aria-hidden="true"></i> Clear</button>                           
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">               
                <div style="color:red">
                    <label id="lblmessage" name="lblmessage">  </label>
                </div>
            </div>
    </div>
    @{Html.RenderPartial("_Repeater", "DeviationRepeater");}
</div>

@section scripts{
    @Scripts.Render("~/bundles/DeviationList")
    <script>
        $(document).ready(function () {
            LoadGrid("DeviationRepeater");
        });
    </script>
}

VistaEDI.2.Web/Views/Parser/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Parser</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <link href="~/Content/bootstrapValidator.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <div class="container clearfix">
            <img src="~/Images/uaclogo.jpg" style="height: auto;width: 350px;" />          
        </div>
    </header><!-- /header -->
    <div class="container">
        <div class="row" style="margin-top:20px">
            <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
                <fieldset>
                    <img src="~/Images/heading.PNG" />

                    @using (Html.BeginForm("Upload", "Parser", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        <div class="row">
                            <div class="col-md-6">                               
                                <input type="file" id="file" name="file" class="hidden" />
                                <input type="text" id="filePathChoose" name="filePathChoose" class="form-control" placeholder='Choose a file...' />
                            </div>
                            <div class="col-md-6">
                                <button class="btn btn-info btn-choose" id="Choose" name="Choose" type="button">Choose</button>
                            </div>
                        </div>

                        <div style="color:red">
                            <label for="" name="lblMessage" id="lblMessage" class="cols-sm-2 control-label">@Html.Raw(ViewBag.Message)</label>
                        </div>
                        <div>
                        <div style="color:blue">
                            <label for="" class="cols-sm-2 control-label">@ViewBag.Status</label>
                        </div>
                            <div class="dropdown">
                                <div class="col-md-6">
                                    <label for="status" control-label">Status</label>
                                    <select name="status" id="status" class="form-control">
                                        <i class="btn btn-default " aria-hidden="true"></i>
                                        <option value="1">Default</option>
                                        <option value="3">Accept on Deviation</option>
                                        <option value="0">Reject on Deviation</option>
                                    </select>
                                </div>
                            </div>
                        <div class="row">                              
                            <div class="col-md-6">
                                <button type="submit" value="Upload" class="btn btn-success" id="btUpload" name="btUpload"><i class="fa fa-upload" aria-hidden="true"></i>Upload</button>
                            </div>
                        </div>                                                    
                        </div>
                    }
                </fieldset>
            </div>
        </div>
    </div>
</body>
</html>

<script src="~/Scripts/jquery-3.1.1.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<script src="~/Scripts/bootbox.min.js"></script>
@*<script src="~/Scripts/rnd.scripts.js"></script>
<script src="~/Scripts/rnd.login.js"></script>*@
<script src="~/Scripts/bootstrapValidator.min.js"></script>
<script src="~/Scripts/Utilities.js"></script>

<script>
    $(document).ready(function () {      

     //   $('#status').attr('data-live-search', 'true');
    //    $('#status').selectpicker();
        $("#Choose").click(function () {
            $('#lblMessage').text('');
            $("#file").click();
            $("#filePathChoose").val($("#file").val());
         
        });

        $("#Reset").click(function () {
            $("#filePathChoose").val("");
        });        
    });
</script>

VistaEDI.2.Web/Views/Parser/IndexBackUp.cshtml
@{

}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Parser</title>
    <style>
           form {
               /* Just to center the form on the page */
               margin: 0 auto;
               width: 400px;
               /* To see the outline of the form */
               padding: 1em;
               border: 1px solid #CCC;
               border-radius: 1em;
           }

               form div + div {
                   margin-top: 1em;
               }

           label {
               /* To make sure that all labels have the same size and are properly aligned */
               display: inline-block;
               width: 90px;
               text-align: right;
           }

           input, textarea {
               /* To make sure that all text fields have the same font settings
        By default, textareas have a monospace font */
               font: 1em sans-serif;
               /* To give the same size to all text fields */
               width: 300px;
               box-sizing: border-box;
               /* To harmonize the look & feel of text field border */
               border: 1px solid #999;
           }

               input:focus, textarea:focus {
                   /* To give a little highlight on active elements */
                   border-color: #000;
               }

           textarea {
               /* To properly align multiline text fields with their labels */
               vertical-align: top;
               /* To give enough room to type some text */
               height: 5em;
           }

           html, body {
               padding: 0;
               margin: 0;
               background: #fafafa;
               text-align: center;
           }

           body {
               padding-top: 4em;
           }

           h1 {
               margin-bottom: 3rem;
               font-family: sans-serif;
               color: #666;
           }

           button {
               width: 300px;
               margin: 20px;
               margin-left: 100px;
           }
    </style>
</head>
<body>
    <div>

        @using (Html.BeginForm("Upload", "Parser", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <label>Choose file:</label> <input type="file" name="file" /><br />
            <div style="color:red">@Html.Raw(ViewBag.Message)</div>
            <div>
                <div style="color:blue">@ViewBag.Status</div>
                <div class="dropdown">
                    <label>Status:</label>
                    <select name="status">
                        <option value="1">Default</option>
                        <option value="3">Accept on Deviation</option>
                        <option value="0">Reject on Deviation</option>
                    </select>
                </div>

                <button type="submit" value="Upload" class="save" id="btnid">Upload</button>
            </div>
        }
    </div>


    @*<script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/Utilities")
    @Scripts.Render("~/bundles/GridUtil")
    @RenderSection("scripts", required: false)*@
</body>
</html>

VistaEDI.2.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>VISTA EDI</title>
    @Styles.Render("~/Content/css")
    @*<script>
        var Api = '@GetApi()';
    </script>*@
</head>
<body class="fuelux">
  
    <div id="wrapper">        
        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="panel panel-primary">
                @RenderBody()
            </div>
        </div>
       @* <input type="hidden" name="hdnToken" id="hdnToken" value="@GetToken()" />*@
        <!-- /#page-content-wrapper -->
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/Utilities")
    @Scripts.Render("~/bundles/GridUtil")
    @RenderSection("scripts", required: false)

</body>
</html>

VistaEDI.2.Web/Views/Shared/_Repeater.cshtml
@model string
<div class="repeater" id="@Model">
    <div id="headerDiv" class="repeater-header">
        @*<div class=""><h4>Search</h4></div>*@
        @HeaderDiv(Model)
    </div>
    <div class="repeater-viewport" style="max-height: 350px;overflow:auto">
        <div class="repeater-canvas"></div>
        <div class="loader repeater-loader"></div>
    </div>
    <div class="repeater-footer">
        <div class="repeater-footer-left">
            <div class="repeater-itemization">
                <span><span class="repeater-start"></span> - <span class="repeater-end"></span> of <span class="repeater-count"></span> items</span>
                <div class="btn-group selectlist dropup" data-resize="auto">
                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                        <span class="selected-label"> </span>
                        <span class="caret"></span>
                        <span class="sr-only">Toggle Dropdown</span>
                    </button>
                    <ul class="dropdown-menu" role="menu">
                        <li data-value="10" data-selected="true"><a href="#">10</a></li>
                        <li data-value="25"><a href="#">25</a></li>
                        <li data-value="50"><a href="#">50</a></li>
                    </ul>
                    <input class="hidden hidden-field" name="itemsPerPage" readonly="readonly" aria-hidden="true" type="text">
                </div>
                <span>Per Page</span>
            </div>
        </div>
        <div class="repeater-footer-right">
            <div class="repeater-pagination">
                <button type="button" class="btn btn-default btn-sm repeater-prev">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                    <span class="sr-only">Previous Page</span>
                </button>
                <label class="page-label" id="myPageLabel">Page</label>
                <div class="repeater-primaryPaging active">
                    <div class="input-group input-append dropdown combobox dropup">
                        <input type="text" class="form-control" aria-labelledby="myPageLabel">
                        <div class="input-group-btn">
                            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                                <span class="caret"></span>
                                <span class="sr-only">Toggle Dropdown</span>
                            </button>
                            <ul class="dropdown-menu dropdown-menu-right"></ul>
                        </div>
                    </div>
                </div>
                <input type="text" class="form-control repeater-secondaryPaging" aria-labelledby="myPageLabel">
                <span>of <span class="repeater-pages"></span></span>
                <button type="button" class="btn btn-default btn-sm repeater-next">
                    <span class="glyphicon glyphicon-chevron-right"></span>
                    <span class="sr-only">Next Page</span>
                </button>
            </div>
        </div>
    </div>
</div>

@helper HeaderDiv(string id)
{
    @* added here 11/15/2016 *@
//if (@id == "DeviationRepeater" || @id == "AssignMaterialRepeater" || @id == "UACRepeater" || @id == "ProcessingMaterialRepeater" || @id == "TestingMaterialRepeater" || @id == "ImportDataRepeater" || @id == "ReportsRepeater")
if (@id == "DeviationRepeater" )
{
    <script>
        var search = document.getElementById('searchDiv');
        if (search) {
            search.style.display = "block";
            document.getElementById('headerDiv').appendChild(search);
        }
    </script>
}
else
{
    <div class="repeater-header-left">
        <div class="repeater-search">
            <div class="search disabled input-group">
                <input type="search" class="form-control" placeholder="Search">
                <span class="input-group-btn">
                    <button class="btn btn-default" type="button">
                        <span class="glyphicon glyphicon-search"></span>
                        <span class="sr-only">Search</span>
                    </button>
                </span>
            </div>
        </div>
    </div>
}
}